name: cli-craft CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env: 
      ZIG_VERSION: "0.14.1" 
      SOURCE_DIR: "src"
      TEST_ROOT_SRC: "src/cli-craft.zig"
      BUILD_DIR: "zig-out"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        run: |
          wget https://ziglang.org/download/${{ env.ZIG_VERSION }}/zig-x86_64-linux-${{ env.ZIG_VERSION }}.tar.xz
          tar -xJf zig-x86_64-linux-${{ env.ZIG_VERSION }}.tar.xz
          ZIG_BIN_PATH="$(pwd)/zig-x86_64-linux-${{ env.ZIG_VERSION }}"
          export PATH="$ZIG_BIN_PATH:$PATH"
          echo "$ZIG_BIN_PATH" >> $GITHUB_PATH
          zig version

      - name: Run build
        run: zig build

      - name: Build tests
        run: zig test ${{ env.TEST_ROOT_SRC }}
